[package]
name = "counting_sort"
version = "0.1.0"
edition = "2021"
author = "silililili"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
